POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{"email": "abdelkaderboukart1@gmail.com", "password": "1a7o2u0t06"}

###

POST http://127.0.0.1:8000/api/signup
Content-Type: application/json

{ "username": "abdelkader", "password": "1a7o2u0t06", "email": "abdelkaderboukart1@gmail.com" }

###

GET http://127.0.0.1:8000/api/test_token
Content-Type: application/json

{ "token" : "c3bd3cc2542af3df2765f3542224d67b108a9b82"}

###

POST http://127.0.0.1:8000/api/logout
Authorization: Token c3bd3cc2542af3df2765f3542224d67b108a9b82
Content-Type: application/json